function [BW,maskedImage] = sparkMaskMorphBright(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 10-Sep-2022
%----------------------------------------------------


% Adjust data to span data range.
X = imadjust(X);

% Threshold image - manual threshold
BW = X > 180;

% Open mask with line
length = 3.000000;
angle = 45.000000;
se = strel('line', length, angle);
BW = imopen(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

